openapi: 3.0.0
info:
  title: Package API
  version: 1.0.0
  description: APIs for managing packages

paths:
  /packages/all:
    get:
      tags:
        - Packages
      summary: Get all packages
      responses:
        '200':
          description: A list of all packages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Package'
        '500':
          description: Internal server error

  /packages/{id}:
    get:
      tags:
        - Packages
      summary: Get a package by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Package ID
          schema:
            type: integer
      responses:
        '200':
          description: The requested package
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
        '404':
          description: Package not found
        '500':
          description: Internal server error

    put:
      tags:
        - Packages
      summary: Update a package by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Package ID
          schema:
            type: integer
        - in: body
          name: package
          required: true
          description: The package data to update
          schema:
            $ref: '#/components/schemas/PackageInput'
      responses:
        '200':
          description: Updated package
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
        '400':
          description: Bad request
        '404':
          description: Package not found
        '500':
          description: Internal server error

    delete:
      tags:
        - Packages
      summary: Delete a package by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Package ID
          schema:
            type: integer
      responses:
        '204':
          description: Package deleted successfully
        '404':
          description: Package not found
        '500':
          description: Internal server error

  /packages:
    post:
      tags:
        - Packages
      summary: Create a new package
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageInput'
      responses:
        '201':
          description: Created package
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
        '400':
          description: Bad request
        '500':
          description: Internal server error

components:
  schemas:
    Package:
      type: object
      properties:
        id:
          type: integer
        allowedConfigTemplates_id:
          type: integer
        name:
          type: string
        days:
          type: integer
        max_usage_gb:
          type: integer
        price:
          type: integer
        status:
          type: string
          enum:
            - active
            - inactive
      required:
        - allowedConfigTemplates_id
        - name
        - days
        - max_usage_gb
        - status

    PackageInput:
      type: object
      properties:
        allowedConfigTemplates_id:
          type: integer
        name:
          type: string
        days:
          type: integer
        max_usage_gb:
          type: integer
        price:
          type: integer
        status:
          type: string
          enum:
            - active
            - inactive
      required:
        - allowedConfigTemplates_id
        - name
        - days
        - max_usage_gb
        - status
