openapi: 3.0.0
info:
  title: ConfigTemplate API
  version: 1.0.0
  description: APIs for managing config templates

paths:
  /packages/all:
    get:
      tags:
        - Packages
      summary: Get all packages
      responses:
        '200':
          description: A list of all packages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Package'
        '500':
          description: Internal server error

  /packages/{id}:
    get:
      tags:
        - Packages
      summary: Get a package by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Package ID
          schema:
            type: integer
      responses:
        '200':
          description: The requested package
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
        '404':
          description: Package not found
        '500':
          description: Internal server error

    put:
      tags:
        - Packages
      summary: Update a package by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Package ID
          schema:
            type: integer
        - in: body
          name: package
          required: true
          description: The package data to update
          schema:
            $ref: '#/components/schemas/PackageInput'
      responses:
        '200':
          description: Updated package
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
        '400':
          description: Bad request
        '404':
          description: Package not found
        '500':
          description: Internal server error

    delete:
      tags:
        - Packages
      summary: Delete a package by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Package ID
          schema:
            type: integer
      responses:
        '204':
          description: Package deleted successfully
        '404':
          description: Package not found
        '500':
          description: Internal server error

  /packages:
    post:
      tags:
        - Packages
      summary: Create a new package
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageInput'
      responses:
        '201':
          description: Created package
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /configTemplates/all:
    get:
      tags:
        - configTemplate
      summary: Get all config templates
      responses:
        '200':
          description: A list of all config templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConfigTemplate'
        '500':
          description: Internal server error

  /configTemplates/{id}:
    get:
      tags:
        - configTemplate
      summary: Get a config template by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Config template ID
          schema:
            type: integer
      responses:
        '200':
          description: The requested config template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigTemplate'
        '404':
          description: Config template not found
        '500':
          description: Internal server error

    put:
      tags:
        - configTemplate
      summary: Update a config template by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Config template ID
          schema:
            type: integer
        - in: body
          name: configTemplate
          required: true
          description: The config template data to update
          schema:
            $ref: '#/components/schemas/ConfigTemplateInput'
      responses:
        '200':
          description: Updated config template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigTemplate'
        '400':
          description
