openapi: 3.0.0
info:
  title: ConfigTemplate API
  version: 1.0.0
  description: APIs for managing config templates

paths:
  /configTemplates/all:
    get:
      tags:
        - configTemplate
      summary: Get all config templates
      responses:
        '200':
          description: A list of all config templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConfigTemplate'
        '500':
          description: Internal server error

  /configTemplates/{id}:
    get:
      tags:
        - configTemplate
      summary: Get a config template by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Config template ID
          schema:
            type: integer
      responses:
        '200':
          description: The requested config template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigTemplate'
        '404':
          description: Config template not found
        '500':
          description: Internal server error

    put:
      tags:
        - configTemplate
      summary: Update a config template by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Config template ID
          schema:
            type: integer
        - in: body
          name: configTemplate
          required: true
          description: The config template data to update
          schema:
            $ref: '#/components/schemas/ConfigTemplateInput'
      responses:
        '200':
          description: Updated config template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigTemplate'
        '400':
          description: Bad request
        '404':
          description: Config template not found
        '500':
          description: Internal server error

    delete:
      tags:
        - configTemplate
      summary: Delete a config template by ID
      parameters:
        - in: path
          name: id
          required: true
          description: Config template ID
          schema:
            type: integer
      responses:
        '204':
          description: Config template deleted successfully
        '404':
          description: Config template not found
        '500':
          description: Internal server error

  /configTemplates:
    post:
      tags:
        - configTemplate
      summary: Create a new config template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigTemplateInput'
      responses:
        '201':
          description: Created config template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigTemplate'
        '400':
          description: Bad request
        '500':
          description: Internal server error

components:
  schemas:
    ConfigTemplate:
      type: object
      properties:
        id:
          type: integer
        template:
          type: string
      required:
        - template

    ConfigTemplateInput:
      type: object
      properties:
        template:
          type: string
      required:
        - template
